using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Volo.Abp.Domain.Repositories;

namespace DMSpro.OMS.MdmService.Customers
{
    public interface ICustomerRepository : IRepository<Customer, Guid>
    {
        Task<CustomerWithNavigationProperties> GetWithNavigationPropertiesAsync(
    Guid id,
    CancellationToken cancellationToken = default
);

        Task<List<CustomerWithNavigationProperties>> GetListWithNavigationPropertiesAsync(
            string filterText = null,
            string code = null,
            string name = null,
            string phone1 = null,
            string phone2 = null,
            string erpCode = null,
            string license = null,
            string taxCode = null,
            string vatName = null,
            string vatAddress = null,
            bool? active = null,
            DateTime? effectiveDateMin = null,
            DateTime? effectiveDateMax = null,
            DateTime? endDateMin = null,
            DateTime? endDateMax = null,
            int? creditLimitMin = null,
            int? creditLimitMax = null,
            bool? isCompany = null,
            Guid? warehouseId = null,
            string street = null,
            string address = null,
            string latitude = null,
            string longitude = null,
            string sfaCustomerCode = null,
            DateTime? lastOrderDateMin = null,
            DateTime? lastOrderDateMax = null,
            Guid? paymentTermId = null,
            Guid? linkedCompanyId = null,
            Guid? priceListId = null,
            Guid? geoMaster0Id = null,
            Guid? geoMaster1Id = null,
            Guid? geoMaster2Id = null,
            Guid? geoMaster3Id = null,
            Guid? geoMaster4Id = null,
            Guid? attribute0Id = null,
            Guid? attribute1Id = null,
            Guid? attribute2Id = null,
            Guid? attribute3Id = null,
            Guid? attribute4Id = null,
            Guid? attribute5Id = null,
            Guid? attribute6Id = null,
            Guid? attribute7Id = null,
            Guid? attribute8Id = null,
            Guid? attribute9Id = null,
            Guid? attribute10Id = null,
            Guid? attribute11Id = null,
            Guid? attribute12Id = null,
            Guid? attribute13Id = null,
            Guid? attribute14Id = null,
            Guid? attribute15Id = null,
            Guid? attribute16Id = null,
            Guid? attribute17Id = null,
            Guid? attribute18Id = null,
            Guid? attribute19Id = null,
            Guid? paymentId = null,
            string sorting = null,
            int maxResultCount = int.MaxValue,
            int skipCount = 0,
            CancellationToken cancellationToken = default
        );

        Task<List<Customer>> GetListAsync(
                    string filterText = null,
                    string code = null,
                    string name = null,
                    string phone1 = null,
                    string phone2 = null,
                    string erpCode = null,
                    string license = null,
                    string taxCode = null,
                    string vatName = null,
                    string vatAddress = null,
                    bool? active = null,
                    DateTime? effectiveDateMin = null,
                    DateTime? effectiveDateMax = null,
                    DateTime? endDateMin = null,
                    DateTime? endDateMax = null,
                    int? creditLimitMin = null,
                    int? creditLimitMax = null,
                    bool? isCompany = null,
                    Guid? warehouseId = null,
                    string street = null,
                    string address = null,
                    string latitude = null,
                    string longitude = null,
                    string sfaCustomerCode = null,
                    DateTime? lastOrderDateMin = null,
                    DateTime? lastOrderDateMax = null,
                    string sorting = null,
                    int maxResultCount = int.MaxValue,
                    int skipCount = 0,
                    CancellationToken cancellationToken = default
                );

        Task<long> GetCountAsync(
            string filterText = null,
            string code = null,
            string name = null,
            string phone1 = null,
            string phone2 = null,
            string erpCode = null,
            string license = null,
            string taxCode = null,
            string vatName = null,
            string vatAddress = null,
            bool? active = null,
            DateTime? effectiveDateMin = null,
            DateTime? effectiveDateMax = null,
            DateTime? endDateMin = null,
            DateTime? endDateMax = null,
            int? creditLimitMin = null,
            int? creditLimitMax = null,
            bool? isCompany = null,
            Guid? warehouseId = null,
            string street = null,
            string address = null,
            string latitude = null,
            string longitude = null,
            string sfaCustomerCode = null,
            DateTime? lastOrderDateMin = null,
            DateTime? lastOrderDateMax = null,
            Guid? paymentTermId = null,
            Guid? linkedCompanyId = null,
            Guid? priceListId = null,
            Guid? geoMaster0Id = null,
            Guid? geoMaster1Id = null,
            Guid? geoMaster2Id = null,
            Guid? geoMaster3Id = null,
            Guid? geoMaster4Id = null,
            Guid? attribute0Id = null,
            Guid? attribute1Id = null,
            Guid? attribute2Id = null,
            Guid? attribute3Id = null,
            Guid? attribute4Id = null,
            Guid? attribute5Id = null,
            Guid? attribute6Id = null,
            Guid? attribute7Id = null,
            Guid? attribute8Id = null,
            Guid? attribute9Id = null,
            Guid? attribute10Id = null,
            Guid? attribute11Id = null,
            Guid? attribute12Id = null,
            Guid? attribute13Id = null,
            Guid? attribute14Id = null,
            Guid? attribute15Id = null,
            Guid? attribute16Id = null,
            Guid? attribute17Id = null,
            Guid? attribute18Id = null,
            Guid? attribute19Id = null,
            Guid? paymentId = null,
            CancellationToken cancellationToken = default);
    }
}