// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.MdmService.Shared;
using DMSpro.OMS.MdmService.WeightMeasurements;
using DMSpro.OMS.Shared.Domain.Devextreme;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.WeightMeasurements;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWeightMeasurementsAppService), typeof(WeightMeasurementClientProxy))]
public partial class WeightMeasurementClientProxy : ClientProxyBase<IWeightMeasurementsAppService>, IWeightMeasurementsAppService
{
    public virtual async Task<PagedResultDto<WeightMeasurementDto>> GetListAsync(GetWeightMeasurementsInput input)
    {
        return await RequestAsync<PagedResultDto<WeightMeasurementDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetWeightMeasurementsInput), input }
        });
    }

    public virtual async Task<WeightMeasurementDto> GetAsync(Guid id)
    {
        return await RequestAsync<WeightMeasurementDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WeightMeasurementDto> CreateAsync(WeightMeasurementCreateDto input)
    {
        return await RequestAsync<WeightMeasurementDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WeightMeasurementCreateDto), input }
        });
    }

    public virtual async Task<WeightMeasurementDto> UpdateAsync(Guid id, WeightMeasurementUpdateDto input)
    {
        return await RequestAsync<WeightMeasurementDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(WeightMeasurementUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(WeightMeasurementExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WeightMeasurementExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<int> UpdateFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(UpdateFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<int> InsertFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(InsertFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<IRemoteStreamContent> GenerateExcelTemplatesAsync()
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GenerateExcelTemplatesAsync));
    }
}
