// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.MdmService.NumberingConfigDetails;
using DMSpro.OMS.Shared.Domain.Devextreme;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.NumberingConfigDetails;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(INumberingConfigDetailsAppService), typeof(NumberingConfigDetailClientProxy))]
public partial class NumberingConfigDetailClientProxy : ClientProxyBase<INumberingConfigDetailsAppService>, INumberingConfigDetailsAppService
{
    public virtual async Task<NumberingConfigDetailDto> GetAsync(Guid id)
    {
        return await RequestAsync<NumberingConfigDetailDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<NumberingConfigDetailDto> CreateAsync(NumberingConfigDetailCreateDto input)
    {
        return await RequestAsync<NumberingConfigDetailDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NumberingConfigDetailCreateDto), input }
        });
    }

    public virtual async Task<NumberingConfigDetailDto> UpdateAsync(Guid id, NumberingConfigDetailUpdateDto input)
    {
        return await RequestAsync<NumberingConfigDetailDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(NumberingConfigDetailUpdateDto), input }
        });
    }

    public virtual async Task<NumberingConfigDetailDto> GetSuggestedNumberingConfigAsync(string objectType, Guid companyId)
    {
        return await RequestAsync<NumberingConfigDetailDto>(nameof(GetSuggestedNumberingConfigAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), objectType },
            { typeof(Guid), companyId }
        });
    }

    public virtual async Task<NumberingConfigDetailDto> SaveNumberingConfigAsync(string objectType, Guid companyId, int currentNumber)
    {
        return await RequestAsync<NumberingConfigDetailDto>(nameof(SaveNumberingConfigAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), objectType },
            { typeof(Guid), companyId },
            { typeof(int), currentNumber }
        });
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<int> UpdateFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(UpdateFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<int> InsertFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(InsertFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<IRemoteStreamContent> GenerateExcelTemplatesAsync()
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GenerateExcelTemplatesAsync));
    }
}
