// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DMSpro.OMS.MdmService.SalesOrders;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.SalesOrders;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISalesOrdersAppService), typeof(SalesOrderClientProxy))]
public partial class SalesOrderClientProxy : ClientProxyBase<ISalesOrdersAppService>, ISalesOrdersAppService
{
    public virtual async Task<string> GetInfoSOAsync(GetInfoSODto input)
    {
        return await RequestAsync<string>(nameof(GetInfoSOAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetInfoSODto), input }
        });
    }
}
