// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using DMSpro.OMS.MdmService.Holidays;
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.Shared.Domain.Devextreme;
using Volo.Abp.Content;
using DMSpro.OMS.MdmService.Shared;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.Holidays.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHolidaysAppService), typeof(HolidayClientProxy))]
public partial class HolidayClientProxy : ClientProxyBase<IHolidaysAppService>, IHolidaysAppService
{
    public virtual async Task<PagedResultDto<HolidayDto>> GetListAsync(GetHolidaysInput input)
    {
        return await RequestAsync<PagedResultDto<HolidayDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetHolidaysInput), input }
        });
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<HolidayDto> GetAsync(Guid id)
    {
        return await RequestAsync<HolidayDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HolidayDto> CreateAsync(HolidayCreateDto input)
    {
        return await RequestAsync<HolidayDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HolidayCreateDto), input }
        });
    }

    public virtual async Task<HolidayDto> UpdateAsync(Guid id, HolidayUpdateDto input)
    {
        return await RequestAsync<HolidayDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HolidayUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(HolidayExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HolidayExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
