// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using DMSpro.OMS.MdmService.ProductAttributes;
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.Shared.Domain.Devextreme;
using Volo.Abp.Content;
using DMSpro.OMS.MdmService.Shared;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.ProductAttributes.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProductAttributesAppService), typeof(ProductAttributeClientProxy))]
public partial class ProductAttributeClientProxy : ClientProxyBase<IProductAttributesAppService>, IProductAttributesAppService
{
    public virtual async Task<PagedResultDto<ProductAttributeDto>> GetListAsync(GetProductAttributesInput input)
    {
        return await RequestAsync<PagedResultDto<ProductAttributeDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetProductAttributesInput), input }
        });
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<ProductAttributeDto> GetAsync(Guid id)
    {
        return await RequestAsync<ProductAttributeDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ProductAttributeDto> CreateAsync(ProductAttributeCreateDto input)
    {
        return await RequestAsync<ProductAttributeDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProductAttributeCreateDto), input }
        });
    }

    public virtual async Task<ProductAttributeDto> UpdateAsync(Guid id, ProductAttributeUpdateDto input)
    {
        return await RequestAsync<ProductAttributeDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ProductAttributeUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(ProductAttributeExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProductAttributeExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
