// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using DMSpro.OMS.MdmService.SystemConfigs;
using Volo.Abp.Content;
using DMSpro.OMS.MdmService.Shared;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.SystemConfigs.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISystemConfigsAppService), typeof(SystemConfigClientProxy))]
public partial class SystemConfigClientProxy : ClientProxyBase<ISystemConfigsAppService>, ISystemConfigsAppService
{
    public virtual async Task<PagedResultDto<SystemConfigDto>> GetListAsync(GetSystemConfigsInput input)
    {
        return await RequestAsync<PagedResultDto<SystemConfigDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetSystemConfigsInput), input }
        });
    }

    public virtual async Task<SystemConfigDto> GetAsync(Guid id)
    {
        return await RequestAsync<SystemConfigDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<SystemConfigDto> CreateAsync(SystemConfigCreateDto input)
    {
        return await RequestAsync<SystemConfigDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SystemConfigCreateDto), input }
        });
    }

    public virtual async Task<SystemConfigDto> UpdateAsync(Guid id, SystemConfigUpdateDto input)
    {
        return await RequestAsync<SystemConfigDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SystemConfigUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(SystemConfigExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SystemConfigExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
