// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using DMSpro.OMS.MdmService.VisitPlans;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.VisitPlans.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IVisitPlansCustomAppService), typeof(VisitPlanCustomClientProxy))]
public partial class VisitPlanCustomClientProxy : ClientProxyBase<IVisitPlansCustomAppService>, IVisitPlansCustomAppService
{
    public virtual async Task<List<VisitPlanDto>> GenerateWithPermissionAsync(VisitPlanGenerationInputDto input)
    {
        return await RequestAsync<List<VisitPlanDto>>(nameof(GenerateWithPermissionAsync), new ClientProxyRequestTypeValue
        {
            { typeof(VisitPlanGenerationInputDto), input }
        });
    }
}
