// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using DMSpro.OMS.MdmService.WeightMeasurements;
using Volo.Abp.Content;
using DMSpro.OMS.MdmService.Shared;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.WeightMeasurements.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWeightMeasurementsAppService), typeof(WeightMeasurementClientProxy))]
public partial class WeightMeasurementClientProxy : ClientProxyBase<IWeightMeasurementsAppService>, IWeightMeasurementsAppService
{
    public virtual async Task<PagedResultDto<WeightMeasurementDto>> GetListAsync(GetWeightMeasurementsInput input)
    {
        return await RequestAsync<PagedResultDto<WeightMeasurementDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetWeightMeasurementsInput), input }
        });
    }

    public virtual async Task<WeightMeasurementDto> GetAsync(Guid id)
    {
        return await RequestAsync<WeightMeasurementDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WeightMeasurementDto> CreateAsync(WeightMeasurementCreateDto input)
    {
        return await RequestAsync<WeightMeasurementDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WeightMeasurementCreateDto), input }
        });
    }

    public virtual async Task<WeightMeasurementDto> UpdateAsync(Guid id, WeightMeasurementUpdateDto input)
    {
        return await RequestAsync<WeightMeasurementDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(WeightMeasurementUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(WeightMeasurementExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WeightMeasurementExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
