// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.MdmService.CustomerImages;
using DMSpro.OMS.MdmService.Shared;
using DMSpro.OMS.Shared.Domain.Devextreme;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.CustomerImages;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ICustomerImagesAppService), typeof(CustomerImageClientProxy))]
public partial class CustomerImageClientProxy : ClientProxyBase<ICustomerImagesAppService>, ICustomerImagesAppService
{
    public virtual async Task<PagedResultDto<CustomerImageWithNavigationPropertiesDto>> GetListAsync(GetCustomerImagesInput input)
    {
        return await RequestAsync<PagedResultDto<CustomerImageWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetCustomerImagesInput), input }
        });
    }

    public virtual async Task<CustomerImageWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<CustomerImageWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CustomerImageDto> GetAsync(Guid id)
    {
        return await RequestAsync<CustomerImageDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetCustomerLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetCustomerLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetItemLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetItemLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(CustomerImageExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CustomerImageExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }

    public virtual async Task DeleteManyAsync(List<Guid> ids)
    {
        await RequestAsync(nameof(DeleteManyAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), ids }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetFileAsync(Guid id)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CustomerImageDto> CreateAsync(Guid customerId, IRemoteStreamContent inputFile, string description, bool active, bool isPOSM, Guid? itemPOSMId)
    {
        return await RequestAsync<CustomerImageDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), customerId },
            { typeof(IRemoteStreamContent), inputFile },
            { typeof(string), description },
            { typeof(bool), active },
            { typeof(bool), isPOSM },
            { typeof(Guid?), itemPOSMId }
        });
    }

    public virtual async Task<CustomerImageDto> UpdateAsync(Guid id, Guid customerId, IRemoteStreamContent inputFile, string description, bool active, bool isPOSM, Guid? itemPOSMId)
    {
        return await RequestAsync<CustomerImageDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(Guid), customerId },
            { typeof(IRemoteStreamContent), inputFile },
            { typeof(string), description },
            { typeof(bool), active },
            { typeof(bool), isPOSM },
            { typeof(Guid?), itemPOSMId }
        });
    }

    public virtual async Task<CustomerImageDto> CreateAvatarAsync(Guid customerId, IRemoteStreamContent inputFile, string description)
    {
        return await RequestAsync<CustomerImageDto>(nameof(CreateAvatarAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), customerId },
            { typeof(IRemoteStreamContent), inputFile },
            { typeof(string), description }
        });
    }

    public virtual async Task<CustomerImageDto> UpdateAvatarAsync(Guid customerId, IRemoteStreamContent inputFile, string description)
    {
        return await RequestAsync<CustomerImageDto>(nameof(UpdateAvatarAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), customerId },
            { typeof(IRemoteStreamContent), inputFile },
            { typeof(string), description }
        });
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<int> UpdateFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(UpdateFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<int> InsertFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(InsertFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<IRemoteStreamContent> GenerateExcelTemplatesAsync()
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GenerateExcelTemplatesAsync));
    }
}
