// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DMSpro.OMS.MdmService.NumberingConfigs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.NumberingConfigs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(INumberingConfigsInternalAppService), typeof(NumberingConfigInternalClientProxy))]
public partial class NumberingConfigInternalClientProxy : ClientProxyBase<INumberingConfigsInternalAppService>, INumberingConfigsInternalAppService
{
    public virtual async Task<List<NumberingConfigDto>> CreateAllConfigsForHostAsync()
    {
        return await RequestAsync<List<NumberingConfigDto>>(nameof(CreateAllConfigsForHostAsync));
    }

    public virtual async Task<List<NumberingConfigDto>> CreateAllConfigsForTenantAsync(List<Guid> tenantIds)
    {
        return await RequestAsync<List<NumberingConfigDto>>(nameof(CreateAllConfigsForTenantAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), tenantIds }
        });
    }

    public virtual async Task<NumberingConfigDto> CreateAsync(NumberingConfigCreateDto input)
    {
        return await RequestAsync<NumberingConfigDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NumberingConfigCreateDto), input }
        });
    }
}
