// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DMSpro.OMS.MdmService.NumberingConfigs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.NumberingConfigs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(INumberingConfigsInternalAppService), typeof(NumberingConfigInternalClientProxy))]
public partial class NumberingConfigInternalClientProxy : ClientProxyBase<INumberingConfigsInternalAppService>, INumberingConfigsInternalAppService
{
    public virtual Task<List<NumberingConfigDto>> CreateAllConfigsForHost()
    {
        //Client Proxy does not support the synchronization method, you should always use asynchronous methods as a best practice
        throw new System.NotImplementedException(); 
    }

    public virtual Task<List<NumberingConfigDto>> CreateAllConfigsForTenant(List<Guid> tenantIds)
    {
        //Client Proxy does not support the synchronization method, you should always use asynchronous methods as a best practice
        throw new System.NotImplementedException(); 
    }

    public virtual Task<NumberingConfigDto> Create(NumberingConfigCreateDto input)
    {
        //Client Proxy does not support the synchronization method, you should always use asynchronous methods as a best practice
        throw new System.NotImplementedException(); 
    }
}
