// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.MdmService.SalesOrgHierarchies;
using DMSpro.OMS.Shared.Domain.Devextreme;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.SalesOrgHierarchies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISalesOrgHierarchiesAppService), typeof(SalesOrgHierarchyClientProxy))]
public partial class SalesOrgHierarchyClientProxy : ClientProxyBase<ISalesOrgHierarchiesAppService>, ISalesOrgHierarchiesAppService
{
    public virtual async Task<SalesOrgHierarchyDto> GetAsync(Guid id)
    {
        return await RequestAsync<SalesOrgHierarchyDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<SalesOrgHierarchyDto> CreateRootAsync(SalesOrgHierarchyCreateRootDto input)
    {
        return await RequestAsync<SalesOrgHierarchyDto>(nameof(CreateRootAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SalesOrgHierarchyCreateRootDto), input }
        });
    }

    public virtual async Task<SalesOrgHierarchyDto> CreateSubAsync(SalesOrgHierarchyCreateSubDto input)
    {
        return await RequestAsync<SalesOrgHierarchyDto>(nameof(CreateSubAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SalesOrgHierarchyCreateSubDto), input }
        });
    }

    public virtual async Task<SalesOrgHierarchyDto> CreateRouteAsync(SalesOrgHierarchyCreateRouteDto input)
    {
        return await RequestAsync<SalesOrgHierarchyDto>(nameof(CreateRouteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SalesOrgHierarchyCreateRouteDto), input }
        });
    }

    public virtual async Task<SalesOrgHierarchyDto> UpdateAsync(Guid id, SalesOrgHierarchyUpdateDto input)
    {
        return await RequestAsync<SalesOrgHierarchyDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SalesOrgHierarchyUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<int> UpdateFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(UpdateFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<int> InsertFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(InsertFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<IRemoteStreamContent> GenerateExcelTemplatesAsync()
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GenerateExcelTemplatesAsync));
    }
}
