// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.MdmService.Shared;
using DMSpro.OMS.MdmService.WorkingPositions;
using DMSpro.OMS.Shared.Domain.Devextreme;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.WorkingPositions;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWorkingPositionsAppService), typeof(WorkingPositionClientProxy))]
public partial class WorkingPositionClientProxy : ClientProxyBase<IWorkingPositionsAppService>, IWorkingPositionsAppService
{
    public virtual async Task<PagedResultDto<WorkingPositionDto>> GetListAsync(GetWorkingPositionsInput input)
    {
        return await RequestAsync<PagedResultDto<WorkingPositionDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetWorkingPositionsInput), input }
        });
    }

    public virtual async Task<WorkingPositionDto> GetAsync(Guid id)
    {
        return await RequestAsync<WorkingPositionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WorkingPositionDto> CreateAsync(WorkingPositionCreateDto input)
    {
        return await RequestAsync<WorkingPositionDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WorkingPositionCreateDto), input }
        });
    }

    public virtual async Task<WorkingPositionDto> UpdateAsync(Guid id, WorkingPositionUpdateDto input)
    {
        return await RequestAsync<WorkingPositionDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(WorkingPositionUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(WorkingPositionExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WorkingPositionExcelDownloadDto), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<int> UpdateFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(UpdateFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<int> InsertFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(InsertFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<IRemoteStreamContent> GenerateExcelTemplatesAsync()
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GenerateExcelTemplatesAsync));
    }
}
