// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DMSpro.OMS.MdmService.PriceUpdates;
using DMSpro.OMS.Shared.Domain.Devextreme;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace DMSpro.OMS.MdmService.Controllers.PriceUpdates;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPriceUpdatesAppService), typeof(PriceUpdateClientProxy))]
public partial class PriceUpdateClientProxy : ClientProxyBase<IPriceUpdatesAppService>, IPriceUpdatesAppService
{
    public virtual async Task<PriceUpdateDto> GetAsync(Guid id)
    {
        return await RequestAsync<PriceUpdateDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PriceUpdateDto> CreateAsync(PriceUpdateCreateDto input)
    {
        return await RequestAsync<PriceUpdateDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PriceUpdateCreateDto), input }
        });
    }

    public virtual async Task<PriceUpdateDto> UpdateAsync(Guid id, PriceUpdateUpdateDto input)
    {
        return await RequestAsync<PriceUpdateDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PriceUpdateUpdateDto), input }
        });
    }

    public virtual async Task<PriceUpdateDto> CancelAsync(Guid id)
    {
        return await RequestAsync<PriceUpdateDto>(nameof(CancelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PriceUpdateDto> ReleaseAsync(Guid id)
    {
        return await RequestAsync<PriceUpdateDto>(nameof(ReleaseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<LoadResult> GetListDevextremesAsync(DataLoadOptionDevextreme inputDev)
    {
        return await RequestAsync<LoadResult>(nameof(GetListDevextremesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataLoadOptionDevextreme), inputDev }
        });
    }

    public virtual async Task<int> UpdateFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(UpdateFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<int> InsertFromExcelAsync(IRemoteStreamContent file)
    {
        return await RequestAsync<int>(nameof(InsertFromExcelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), file }
        });
    }

    public virtual async Task<IRemoteStreamContent> GenerateExcelTemplatesAsync()
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GenerateExcelTemplatesAsync));
    }
}
